### ISSUE TITLE
/*WA JAVA PROGRAM TO DISPLAY PATTERN 1 12 123 1234 12345 1234 123 12 1 */

### ISSUE THREAD

**Issue by Shahzad0123** [shahnawazm786/Al_Khozaimi_Batch#21]
/*WA JAVA PROGRAM TO DISPLAY PATTERN
1
12
123
1234
12345
1234
123
12
1
*/

package javaprogram;

import javax.sound.midi.SysexMessage;

public class SeriesDiamondDigit 
{

	public static void main(String[] args) 
	{
		int i=1,j;
		while(i<=5)    // LOOP FOR UPPER ROW 1 to 5.
		{
			j=1;
			while(j<=i)   // LOOP FOR COLUMN
			{
				System.out.print(j);
				j++;
			}
			System.out.println();
			i++;
		}
		
	int z=5;
		while(z>=1) // LOOP FOR ROW
		{
			int k=1;
			while(k<z)// LOOP FOR COLUMN
			{
				System.out.print(k);
				k++;
			}
			System.out.println();
			z--;
		}
		
		
	}

}

**Comment by kasif22raza** [comment]
/*WA JAVA PROGRAM TO DISPLAY PATTERN

1
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 

*/

package myprogram;

public class NumberTriangleUsingWhileLoop {
	public static void main(String[] args)
	{	
		int rows =7;
		//	outermost loop to represent the number of rows which is 7 in this case
		//for the upper half of arrow
		
		int i=1;
		int j=1;
		while(i<=rows-2)
		{
			i++;
			//innermost loop is to print the numbers in the specific rows
			//for the upper half of arrow
		
			j=1;			
			while(j<=i)		
			{
			
				System.out.print(j + " ");
				j++;
			}
			System.out.println();
		}
		//outermost loop to represent the number of rows which is 6 in this case
		//for the lower half of arrow
	
		i=rows-1;	
		while(i>=1)
		{
			i--;
		//innermost loop is to print the numbers in the specific rows
		//for the lower half of arrow
	
			j=1;
			while(j<=i)
		{
		System.out.print(j + " ");
		j++;
		}
		System.out.println();
		}
	}
}
